
services:

  db:
    image: mysql:8

    container_name: athletelab_bd

    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: athletelab

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d/

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

  app:
    build: .

    container_name: athletelab-app

    #Essas duas linhas permitem escrever no terminal Docker
    stdin_open: true
    tty: true

    restart: on-failure
    depends_on:
      db:
        condition: service_healthy

    environment:
      DB_HOST: db

volumes:
  mysql_data:

